from sqlalchemy import create_engine, Column, Integer, String, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

Base = declarative_base()

# Define the Question model
class Question(Base):
    __tablename__ = 'questions'
    id = Column(Integer, primary_key=True, autoincrement=True)
    question_text = Column(String, nullable=False)
    option_a = Column(String, nullable=False)
    option_b = Column(String, nullable=False)
    option_c = Column(String, nullable=False)
    option_d = Column(String, nullable=False)
    correct_option = Column(String, nullable=False)  # Store the correct option (e.g., 'A')

# Database setup
def setup_database():
    engine = create_engine('sqlite:///quiz.db')  # Using SQLite for simplicity
    Base.metadata.create_all(engine)
    return engine

# Add sample questions to the database
def add_sample_questions(session):
    sample_questions = [
        # ##############################
    Question(
        question_text="Which gas is necessary for photosynthesis?",
        option_a="Oxygen",
        option_b="Nitrogen",
        option_c="Carbon Dioxide",
        option_d="Hydrogen",
        correct_option="C",
    ),
    Question(
        question_text="What is the powerhouse of the cell?",
        option_a="Nucleus",
        option_b="Mitochondria",
        option_c="Ribosome",
        option_d="Golgi apparatus",
        correct_option="B",
    ),
    Question(
        question_text="What is the capital of Japan?",
        option_a="Beijing",
        option_b="Seoul",
        option_c="Tokyo",
        option_d="Bangkok",
        correct_option="C",
    ),
    Question(
        question_text="What is the smallest planet in our solar system?",
        option_a="Earth",
        option_b="Mars",
        option_c="Venus",
        option_d="Mercury",
        correct_option="D",
    ),
    Question(
        question_text="What is the chemical symbol for gold?",
        option_a="Au",
        option_b="Ag",
        option_c="Pb",
        option_d="Fe",
        correct_option="A",
    ),
    Question(
        question_text="Who wrote 'To Kill a Mockingbird'?",
        option_a="Harper Lee",
        option_b="Mark Twain",
        option_c="Ernest Hemingway",
        option_d="F. Scott Fitzgerald",
        correct_option="A",
    ),
    Question(
        question_text="Which element has the atomic number 1?",
        option_a="Oxygen",
        option_b="Helium",
        option_c="Hydrogen",
        option_d="Nitrogen",
        correct_option="C",
    ),
    Question(
        question_text="What is the hardest natural substance on Earth?",
        option_a="Gold",
        option_b="Iron",
        option_c="Diamond",
        option_d="Platinum",
        correct_option="C",
    ),
    Question(
        question_text="Who painted the Mona Lisa?",
        option_a="Vincent van Gogh",
        option_b="Pablo Picasso",
        option_c="Leonardo da Vinci",
        option_d="Claude Monet",
        correct_option="C",
    ),
    Question(
        question_text="What is the longest river in the world?",
        option_a="Amazon River",
        option_b="Nile River",
        option_c="Yangtze River",
        option_d="Mississippi River",
        correct_option="B",
    ),
    Question(
        question_text="Which planet is known as the Red Planet?",
        option_a="Earth",
        option_b="Jupiter",
        option_c="Mars",
        option_d="Saturn",
        correct_option="C",
    ),
    Question(
        question_text="What is the boiling point of water at sea level?",
        option_a="90°C",
        option_b="100°C",
        option_c="110°C",
        option_d="120°C",
        correct_option="B",
    ),
    Question(
        question_text="Which country is the largest by land area?",
        option_a="Canada",
        option_b="China",
        option_c="United States",
        option_d="Russia",
        correct_option="D",
    ),
    Question(
        question_text="What is the main ingredient in traditional Japanese miso soup?",
        option_a="Soybean paste",
        option_b="Rice",
        option_c="Tofu",
        option_d="Seaweed",
        correct_option="A",
    ),
    Question(
        question_text="Which organ is responsible for pumping blood throughout the human body?",
        option_a="Liver",
        option_b="Lungs",
        option_c="Brain",
        option_d="Heart",
        correct_option="D",
    ),
    Question(
        question_text="Which planet has the most moons?",
        option_a="Earth",
        option_b="Mars",
        option_c="Jupiter",
        option_d="Saturn",
        correct_option="C",
    ),
    Question(
        question_text="Who developed the theory of relativity?",
        option_a="Isaac Newton",
        option_b="Albert Einstein",
        option_c="Galileo Galilei",
        option_d="Nikola Tesla",
        correct_option="B",
    ),
    Question(
        question_text="What is the currency of Japan?",
        option_a="Yen",
        option_b="Won",
        option_c="Peso",
        option_d="Dollar",
        correct_option="A",
    ),
    Question(
        question_text="Which vitamin is produced when a person is exposed to sunlight?",
        option_a="Vitamin A",
        option_b="Vitamin B",
        option_c="Vitamin C",
        option_d="Vitamin D",
        correct_option="D",
    ),
    Question(
        question_text="What is the largest mammal in the world?",
        option_a="Elephant",
        option_b="Blue Whale",
        option_c="Giraffe",
        option_d="Hippopotamus",
        correct_option="B",
    ),
    Question(
        question_text="Who is known as the Father of Computers?",
        option_a="Charles Babbage",
        option_b="Alan Turing",
        option_c="John von Neumann",
        option_d="Bill Gates",
        correct_option="A",
    ),
    Question(
        question_text="What is the capital of Australia?",
        option_a="Sydney",
        option_b="Melbourne",
        option_c="Canberra",
        option_d="Brisbane",
        correct_option="C",
    ),
    Question(
        question_text="Which planet is closest to the sun?",
        option_a="Venus",
        option_b="Mercury",
        option_c="Earth",
        option_d="Mars",
        correct_option="B",
    ),
    Question(
        question_text="What is the chemical formula for water?",
        option_a="H2O",
        option_b="CO2",
        option_c="NaCl",
        option_d="O2",
        correct_option="A",
    ),
    Question(
        question_text="Which organ is primarily responsible for detoxification in the human body?",
        option_a="Heart",
        option_b="Liver",
        option_c="Kidneys",
        option_d="Lungs",
        correct_option="B",
    ),
    Question(
        question_text="Who wrote '1984'?",
        option_a="George Orwell",
        option_b="Aldous Huxley",
        option_c="Ray Bradbury",
        option_d="Jules Verne",
        correct_option="A",
    ),
    Question(
        question_text="What is the largest ocean on Earth?",
        option_a="Atlantic Ocean",
        option_b="Indian Ocean",
        option_c="Arctic Ocean",
        option_d="Pacific Ocean",
        correct_option="D",
    ),
    Question(
        question_text="Which country won the FIFA World Cup in 2018?",
        option_a="Germany",
        option_b="Brazil",
        option_c="France",
        option_d="Argentina",
        correct_option="C",
    ),
    Question(
        question_text="What is the most abundant gas in the Earth's atmosphere?",
        option_a="Oxygen",
        option_b="Nitrogen",
        option_c="Carbon Dioxide",
        option_d="Hydrogen",
        correct_option="B",
    ),
    Question(
        question_text="Which element is known as the 'King of Metals'?",
        option_a="Gold",
        option_b="Silver",
        option_c="Iron",
        option_d="Platinum",
        correct_option="A",
    ),
    Question(
        question_text="Who is the author of 'Pride and Prejudice'?",
        option_a="Emily Brontë",
        option_b="Mary Shelley",
        option_c="Jane Austen",
        option_d="Charlotte Brontë",
        correct_option="C",
    ),
    Question(
        question_text="What is the speed of light in a vacuum?",
        option_a="300,000 km/s",
        option_b="150,000 km/s",
        option_c="450,000 km/s",
        option_d="600,000 km/s",
        correct_option="A",
    ),
    Question(
        question_text="Which country is known as the Land of the Rising Sun?",
        option_a="China",
        option_b="Japan",
        option_c="Thailand",
        option_d="South Korea",
        correct_option="B",
    ),
    Question(
        question_text="Which organ in the human body is responsible for producing insulin?",
        option_a="Liver",
        option_b="Pancreas",
        option_c="Kidneys",
        option_d="Stomach",
        correct_option="B",
    ),
    Question(
        question_text="Who discovered penicillin?",
        option_a="Alexander Fleming",
        option_b="Marie Curie",
        option_c="Isaac Newton",
        option_d="Albert Einstein",
        correct_option="A",
    ),
    Question(
        question_text="What is the capital of Canada?",
        option_a="Toronto",
        option_b="Vancouver",
        option_c="Ottawa",
        option_d="Montreal",
        correct_option="C",
    ),
    Question(
        question_text="Which planet is known for its rings?",
        option_a="Jupiter",
        option_b="Saturn",
        option_c="Uranus",
        option_d="Neptune",
        correct_option="B",
    ),
    Question(
        question_text="What is the hardest known natural material?",
        option_a="Gold",
        option_b="Silver",
        option_c="Iron",
        option_d="Diamond",
        correct_option="D",
    ),
    Question(
        question_text="Which famous scientist introduced the concept of natural selection?",
        option_a="Isaac Newton",
        option_b="Albert Einstein",
        option_c="Charles Darwin",
        option_d="Galileo Galilei",
        correct_option="C",
    ),
    Question(
        question_text="What is the largest bone in the human body?",
        option_a="Skull",
        option_b="Femur",
        option_c="Humerus",
        option_d="Spine",
        correct_option="B",
    ),
    Question(
        question_text="What is the longest bone in the human body?",
        option_a="Humerus",
        option_b="Femur",
        option_c="Tibia",
        option_d="Fibula",
        correct_option="B",
    ),
    Question(
        question_text="Who is the author of 'Harry Potter' series?",
        option_a="J.K. Rowling",
        option_b="J.R.R. Tolkien",
        option_c="George R.R. Martin",
        option_d="C.S. Lewis",
        correct_option="A",
    ),
    Question(
        question_text="Which planet is known as the Earth's twin?",
        option_a="Mars",
        option_b="Venus",
        option_c="Jupiter",
        option_d="Saturn",
        correct_option="B",
    ),
    Question(
        question_text="What is the capital of Italy?",
        option_a="Rome",
        option_b="Milan",
        option_c="Venice",
        option_d="Florence",
        correct_option="A",
    ),
    Question(
        question_text="What is the freezing point of water?",
        option_a="0°C",
        option_b="32°C",
        option_c="100°C",
        option_d="212°C",
        correct_option="A",
    ),
    Question(
        question_text="What is the largest continent on Earth?",
        option_a="Africa",
        option_b="North America",
        option_c="Asia",
        option_d="Europe",
        correct_option="C",
    ),
    Question(
        question_text="Which organ is primarily responsible for filtering blood?",
        option_a="Heart",
        option_b="Lungs",
        option_c="Liver",
        option_d="Kidneys",
        correct_option="D",
    ),
    Question(
        question_text="What is the chemical symbol for sodium?",
        option_a="S",
        option_b="Na",
        option_c="K",
        option_d="Si",
        correct_option="B",
    ),
    Question(
        question_text="Which gas is known as laughing gas?",
        option_a="Nitrogen",
        option_b="Carbon Dioxide",
        option_c="Nitrous Oxide",
        option_d="Oxygen",
        correct_option="C",
    ),
    Question(
        question_text="Who painted the ceiling of the Sistine Chapel?",
        option_a="Leonardo da Vinci",
        option_b="Michelangelo",
        option_c="Raphael",
        option_d="Donatello",
        correct_option="B",
    ),
    Question(
        question_text="What is the name of the first artificial Earth satellite launched by the Soviet Union in 1957?",
        option_a="Voyager",
        option_b="Hubble",
        option_c="Sputnik",
        option_d="Apollo",
        correct_option="C",
    ),
    Question(
        question_text="Which country is known as the Land of the Thunder Dragon?",
        option_a="Nepal",
        option_b="Bhutan",
        option_c="Thailand",
        option_d="Mongolia",
        correct_option="B",
    ),
     Question(
        question_text="Which animal is known as the King of the Jungle?",
        option_a="Lion",
        option_b="Tiger",
        option_c="Elephant",
        option_d="Gorilla",
        correct_option="A",
    ),
    Question(
        question_text="What is the capital of France?",
        option_a="Berlin",
        option_b="Madrid",
        option_c="Rome",
        option_d="Paris",
        correct_option="D",
    ),
    Question(
        question_text="Which element has the chemical symbol 'Fe'?",
        option_a="Lead",
        option_b="Iron",
        option_c="Gold",
        option_d="Silver",
        correct_option="B",
    ),
    Question(
        question_text="Which planet is known as the Red Planet?",
        option_a="Venus",
        option_b="Jupiter",
        option_c="Mars",
        option_d="Saturn",
        correct_option="C",
    ),
    Question(
        question_text="What is the largest mammal in the world?",
        option_a="Elephant",
        option_b="Blue Whale",
        option_c="Giraffe",
        option_d="Hippopotamus",
        correct_option="B",
    ),
    Question(
        question_text="Who is the author of 'To Kill a Mockingbird'?",
        option_a="Harper Lee",
        option_b="F. Scott Fitzgerald",
        option_c="Ernest Hemingway",
        option_d="Mark Twain",
        correct_option="A",
    ),
    Question(
        question_text="What is the smallest prime number?",
        option_a="0",
        option_b="1",
        option_c="2",
        option_d="3",
        correct_option="C",
    ),
    Question(
        question_text="Which vitamin is produced when a person is exposed to sunlight?",
        option_a="Vitamin A",
        option_b="Vitamin B",
        option_c="Vitamin C",
        option_d="Vitamin D",
        correct_option="D",
    ),
    Question(
        question_text="Who was the first President of the United States?",
        option_a="Abraham Lincoln",
        option_b="George Washington",
        option_c="Thomas Jefferson",
        option_d="John Adams",
        correct_option="B",
    ),
    Question(
        question_text="Which gas do plants absorb from the atmosphere?",
        option_a="Oxygen",
        option_b="Nitrogen",
        option_c="Carbon Dioxide",
        option_d="Hydrogen",
        correct_option="C",
    ),
    Question(
        question_text="Who painted the Mona Lisa?",
        option_a="Vincent van Gogh",
        option_b="Claude Monet",
        option_c="Pablo Picasso",
        option_d="Leonardo da Vinci",
        correct_option="D",
    ),
    Question(
        question_text="Which planet has the most moons?",
        option_a="Earth",
        option_b="Mars",
        option_c="Jupiter",
        option_d="Saturn",
        correct_option="C",
    ),
    Question(
        question_text="What is the hardest natural substance on Earth?",
        option_a="Gold",
        option_b="Iron",
        option_c="Diamond",
        option_d="Silver",
        correct_option="C",
    ),
    Question(
        question_text="Which continent is the Sahara Desert located on?",
        option_a="Asia",
        option_b="Africa",
        option_c="Australia",
        option_d="South America",
        correct_option="B",
    ),
    Question(
        question_text="Who developed the theory of relativity?",
        option_a="Isaac Newton",
        option_b="Galileo Galilei",
        option_c="Albert Einstein",
        option_d="Nikola Tesla",
        correct_option="C",
    ),
    Question(
        question_text="What is the largest planet in our solar system?",
        option_a="Earth",
        option_b="Jupiter",
        option_c="Saturn",
        option_d="Neptune",
        correct_option="B",
    ),
    Question(
        question_text="Which ocean is the largest?",
        option_a="Atlantic Ocean",
        option_b="Indian Ocean",
        option_c="Arctic Ocean",
        option_d="Pacific Ocean",
        correct_option="D",
    ),
    Question(
        question_text="What is the powerhouse of the cell?",
        option_a="Nucleus",
        option_b="Ribosome",
        option_c="Mitochondria",
        option_d="Golgi apparatus",
        correct_option="C",
    ),
    Question(
        question_text="Who wrote the play 'Romeo and Juliet'?",
        option_a="Charles Dickens",
        option_b="George Orwell",
        option_c="William Shakespeare",
        option_d="Jane Austen",
        correct_option="C",
    ),
    Question(
        question_text="What is the main ingredient in guacamole?",
        option_a="Tomato",
        option_b="Onion",
        option_c="Avocado",
        option_d="Pepper",
        correct_option="C",
    ),
    Question(
        question_text="Which country is the largest by land area?",
        option_a="Canada",
        option_b="China",
        option_c="Russia",
        option_d="United States",
        correct_option="C",
    ),
    Question(
        question_text="What is the chemical symbol for gold?",
        option_a="Au",
        option_b="Ag",
        option_c="Pb",
        option_d="Pt",
        correct_option="A",
    ),
    Question(
        question_text="Which organ pumps blood throughout the body?",
        option_a="Lungs",
        option_b="Brain",
        option_c="Heart",
        option_d="Liver",
        correct_option="C",
    ),
    Question(
        question_text="Who invented the telephone?",
        option_a="Thomas Edison",
        option_b="Nikola Tesla",
        option_c="Alexander Graham Bell",
        option_d="Guglielmo Marconi",
        correct_option="C",
    ),
    Question(
        question_text="What is the main gas found in the air we breathe?",
        option_a="Oxygen",
        option_b="Carbon Dioxide",
        option_c="Nitrogen",
        option_d="Hydrogen",
        correct_option="C",
    ),
    Question(
        question_text="What is the largest internal organ in the human body?",
        option_a="Brain",
        option_b="Liver",
        option_c="Heart",
        option_d="Kidney",
        correct_option="B",
    ),
    Question(
        question_text="Who was the first man to step on the moon?",
        option_a="Buzz Aldrin",
        option_b="Michael Collins",
        option_c="Yuri Gagarin",
        option_d="Neil Armstrong",
        correct_option="D",
    ),
    Question(
        question_text="What is the square root of 144?",
        option_a="10",
        option_b="12",
        option_c="14",
        option_d="16",
        correct_option="B",
    ),
    Question(
        question_text="Which country gifted the Statue of Liberty to the United States?",
        option_a="France",
        option_b="Spain",
        option_c="Italy",
        option_d="Germany",
        correct_option="A",
    ),
    Question(
        question_text="What is the smallest country in the world?",
        option_a="Monaco",
        option_b="Vatican City",
        option_c="San Marino",
        option_d="Liechtenstein",
        correct_option="B",
    ),
    Question(
        question_text="Which planet is known as the Morning Star or the Evening Star?",
        option_a="Mars",
        option_b="Venus",
        option_c="Mercury",
        option_d="Jupiter",
        correct_option="B",
    ),
     Question(
        question_text="What is the capital of Japan?",
        option_a="Beijing",
        option_b="Seoul",
        option_c="Tokyo",
        option_d="Bangkok",
        correct_option="C",
    ),
    Question(
        question_text="Who developed the first successful airplane?",
        option_a="Thomas Edison",
        option_b="Orville and Wilbur Wright",
        option_c="Charles Lindbergh",
        option_d="Leonardo da Vinci",
        correct_option="B",
    ),
    Question(
        question_text="What is the largest desert in the world?",
        option_a="Sahara",
        option_b="Kalahari",
        option_c="Arabian",
        option_d="Antarctic",
        correct_option="D",
    ),
    Question(
        question_text="Which organ is primarily responsible for pumping blood?",
        option_a="Brain",
        option_b="Heart",
        option_c="Lungs",
        option_d="Kidney",
        correct_option="B",
    ),
    Question(
        question_text="Which continent is also a country?",
        option_a="Asia",
        option_b="Australia",
        option_c="Africa",
        option_d="Europe",
        correct_option="B",
    ),
    Question(
        question_text="What is the currency of the United Kingdom?",
        option_a="Euro",
        option_b="Pound Sterling",
        option_c="Yen",
        option_d="Dollar",
        correct_option="B",
    ),
    Question(
        question_text="What is the capital of Canada?",
        option_a="Ottawa",
        option_b="Toronto",
        option_c="Vancouver",
        option_d="Montreal",
        correct_option="A",
    ),
    Question(
        question_text="Which planet is closest to the Sun?",
        option_a="Earth",
        option_b="Mercury",
        option_c="Venus",
        option_d="Mars",
        correct_option="B",
    ),
    Question(
        question_text="Which animal is the largest land mammal?",
        option_a="Elephant",
        option_b="Rhino",
        option_c="Giraffe",
        option_d="Hippo",
        correct_option="A",
    ),
    Question(
        question_text="Who invented the lightbulb?",
        option_a="Thomas Edison",
        option_b="Alexander Graham Bell",
        option_c="Nikola Tesla",
        option_d="Benjamin Franklin",
        correct_option="A",
    ),
    Question(
        question_text="What is the longest river in the world?",
        option_a="Amazon",
        option_b="Nile",
        option_c="Yangtze",
        option_d="Mississippi",
        correct_option="B",
    ),
    Question(
        question_text="Who wrote the novel '1984'?",
        option_a="Aldous Huxley",
        option_b="George Orwell",
        option_c="Ernest Hemingway",
        option_d="Mark Twain",
        correct_option="B",
    ),
    Question(
        question_text="What is the chemical symbol for water?",
        option_a="H2O",
        option_b="O2",
        option_c="CO2",
        option_d="H2",
        correct_option="A",
    ),
    Question(
        question_text="What is the largest island in the world?",
        option_a="Australia",
        option_b="Greenland",
        option_c="New Guinea",
        option_d="Borneo",
        correct_option="B",
    ),
    Question(
        question_text="Who was the first woman to win a Nobel Prize?",
        option_a="Marie Curie",
        option_b="Rosalind Franklin",
        option_c="Ada Lovelace",
        option_d="Lise Meitner",
        correct_option="A",
    ),
    Question(
        question_text="In which country would you find the Great Barrier Reef?",
        option_a="Australia",
        option_b="United States",
        option_c="South Africa",
        option_d="Brazil",
        correct_option="A",
    ),
    Question(
        question_text="What is the main ingredient in traditional Japanese miso soup?",
        option_a="Soybeans",
        option_b="Rice",
        option_c="Fish",
        option_d="Seaweed",
        correct_option="A",
    ),
    Question(
        question_text="Who painted the famous artwork 'Starry Night'?",
        option_a="Pablo Picasso",
        option_b="Vincent van Gogh",
        option_c="Claude Monet",
        option_d="Leonardo da Vinci",
        correct_option="B",
    ),
    Question(
        question_text="What type of animal is the largest species of shark?",
        option_a="Great White Shark",
        option_b="Whale Shark",
        option_c="Hammerhead Shark",
        option_d="Tiger Shark",
        correct_option="B",
    ),
    Question(
        question_text="Which country is known as the Land of the Rising Sun?",
        option_a="China",
        option_b="South Korea",
        option_c="Japan",
        option_d="Vietnam",
        correct_option="C",
    ),
    Question(
        question_text="Which element is the main component of natural gas?",
        option_a="Methane",
        option_b="Carbon Dioxide",
        option_c="Propane",
        option_d="Hydrogen",
        correct_option="A",
    ),
    Question(
        question_text="Which animal is known for its ability to regenerate lost limbs?",
        option_a="Octopus",
        option_b="Starfish",
        option_c="Lizard",
        option_d="Frog",
        correct_option="B",
    ),
    Question(
        question_text="What is the most common element in the Earth's crust?",
        option_a="Iron",
        option_b="Oxygen",
        option_c="Silicon",
        option_d="Carbon",
        correct_option="B",
    ),
    Question(
        question_text="Who is credited with discovering penicillin?",
        option_a="Louis Pasteur",
        option_b="Marie Curie",
        option_c="Alexander Fleming",
        option_d="Robert Hooke",
        correct_option="C",
    ),
    Question(
        question_text="What is the chemical symbol for helium?",
        option_a="He",
        option_b="H",
        option_c="Li",
        option_d="Ho",
        correct_option="A",
    ),
    Question(
        question_text="What is the primary source of energy for the Earth?",
        option_a="The Moon",
        option_b="The Sun",
        option_c="The Stars",
        option_d="Volcanic Activity",
        correct_option="B",
    ),
    Question(
        question_text="What is the national flower of Japan?",
        option_a="Rose",
        option_b="Tulip",
        option_c="Cherry Blossom",
        option_d="Lotus",
        correct_option="C",
    ),
    Question(
        question_text="Which element is used to make the lightest metal alloy, often used in airplanes?",
        option_a="Aluminum",
        option_b="Iron",
        option_c="Titanium",
        option_d="Magnesium",
        correct_option="A",
    ),
    Question(
        question_text="Which ancient civilization built the pyramids?",
        option_a="Roman",
        option_b="Egyptian",
        option_c="Mayan",
        option_d="Inca",
        correct_option="B",
    ),
    Question(
        question_text="What does the word 'photo' in photography refer to?",
        option_a="Light",
        option_b="Color",
        option_c="Camera",
        option_d="Lens",
        correct_option="A",
    ),
    Question(
        question_text="Which bird is known for its ability to mimic human speech?",
        option_a="Parrot",
        option_b="Crow",
        option_c="Eagle",
        option_d="Sparrow",
        correct_option="A",
    ),
    Question(
        question_text="What is the longest running TV show?",
        option_a="Friends",
        option_b="The Simpsons",
        option_c="The Office",
        option_d="Saturday Night Live",
        correct_option="B",
    ),
    Question(
        question_text="What is the smallest bone in the human body?",
        option_a="Stapes",
        option_b="Femur",
        option_c="Tibia",
        option_d="Radius",
        correct_option="A",
    ),
    Question(
        question_text="Which popular fruit is classified as a berry?",
        option_a="Apple",
        option_b="Strawberry",
        option_c="Banana",
        option_d="Tomato",
        correct_option="D",
    ),
    Question(
        question_text="What is the fastest land animal?",
        option_a="Lion",
        option_b="Cheetah",
        option_c="Leopard",
        option_d="Elephant",
        correct_option="B",
    ),
    Question(
        question_text="Which country invented pizza?",
        option_a="Italy",
        option_b="France",
        option_c="Spain",
        option_d="United States",
        correct_option="A",
    ),
    Question(
        question_text="Which organ produces insulin in the human body?",
        option_a="Liver",
        option_b="Kidney",
        option_c="Pancreas",
        option_d="Lungs",
        correct_option="C",
    ),
    Question(
        question_text="Which famous scientist developed the laws of motion?",
        option_a="Isaac Newton",
        option_b="Albert Einstein",
        option_c="Galileo Galilei",
        option_d="Nikola Tesla",
        correct_option="A",
    ),
    Question(
        question_text="Which element is most commonly used in batteries?",
        option_a="Copper",
        option_b="Lithium",
        option_c="Nickel",
        option_d="Aluminum",
        correct_option="B",
    ),
    Question(
        question_text="Which tree produces acorns?",
        option_a="Oak",
        option_b="Pine",
        option_c="Maple",
        option_d="Birch",
        correct_option="A",
    ),
    Question(
        question_text="What is the name of the river that flows through Egypt?",
        option_a="Amazon",
        option_b="Mississippi",
        option_c="Nile",
        option_d="Yangtze",
        correct_option="C",
    ),
    Question(
        question_text="What is the capital city of France?",
        option_a="Rome",
        option_b="Berlin",
        option_c="Paris",
        option_d="Madrid",
        correct_option="C",
    ),
    Question(
        question_text="Which planet is known as the Red Planet?",
        option_a="Earth",
        option_b="Mars",
        option_c="Jupiter",
        option_d="Venus",
        correct_option="B",
    ),
     Question(
        question_text="Which country is known as the Land of the Midnight Sun?",
        option_a="Finland",
        option_b="Norway",
        option_c="Sweden",
        option_d="Iceland",
        correct_option="B",
    ),
    Question(
        question_text="What is the hardest natural substance on Earth?",
        option_a="Gold",
        option_b="Diamond",
        option_c="Iron",
        option_d="Platinum",
        correct_option="B",
    ),
    Question(
        question_text="What is the main ingredient in guacamole?",
        option_a="Tomato",
        option_b="Onion",
        option_c="Avocado",
        option_d="Lemon",
        correct_option="C",
    ),
    Question(
        question_text="Which planet is known as the Morning Star?",
        option_a="Venus",
        option_b="Mars",
        option_c="Saturn",
        option_d="Jupiter",
        correct_option="A",
    ),
    Question(
        question_text="Which country is the origin of the Olympic Games?",
        option_a="Italy",
        option_b="Greece",
        option_c="France",
        option_d="Germany",
        correct_option="B",
    ),
    Question(
        question_text="What is the capital of Spain?",
        option_a="Lisbon",
        option_b="Barcelona",
        option_c="Madrid",
        option_d="Seville",
        correct_option="C",
    ),
    Question(
        question_text="What is the smallest country in the world by land area?",
        option_a="Monaco",
        option_b="San Marino",
        option_c="Vatican City",
        option_d="Liechtenstein",
        correct_option="C",
    ),
    Question(
        question_text="Which bird is the fastest flying bird?",
        option_a="Peregrine Falcon",
        option_b="Eagle",
        option_c="Hummingbird",
        option_d="Albatross",
        correct_option="A",
    ),
    Question(
        question_text="Who was the first President of the United States?",
        option_a="George Washington",
        option_b="Abraham Lincoln",
        option_c="Thomas Jefferson",
        option_d="John Adams",
        correct_option="A",
    ),
    Question(
        question_text="What is the national sport of Japan?",
        option_a="Baseball",
        option_b="Sumo Wrestling",
        option_c="Football",
        option_d="Judo",
        correct_option="B",
    ),
    Question(
        question_text="Which element has the chemical symbol 'O'?",
        option_a="Oxygen",
        option_b="Osmium",
        option_c="Ozone",
        option_d="Oganesson",
        correct_option="A",
    ),
    Question(
        question_text="What is the longest running Broadway musical?",
        option_a="Les Misérables",
        option_b="The Phantom of the Opera",
        option_c="Cats",
        option_d="Chicago",
        correct_option="B",
    ),
    Question(
        question_text="What is the largest ocean on Earth?",
        option_a="Atlantic Ocean",
        option_b="Indian Ocean",
        option_c="Arctic Ocean",
        option_d="Pacific Ocean",
        correct_option="D",
    ),
    Question(
        question_text="Which element is commonly used in the production of semiconductors?",
        option_a="Gold",
        option_b="Silicon",
        option_c="Iron",
        option_d="Copper",
        correct_option="B",
    ),
    Question(
        question_text="What is the primary color of the flag of Japan?",
        option_a="Red",
        option_b="Blue",
        option_c="White",
        option_d="Green",
        correct_option="A",
    ),
    Question(
        question_text="Which country invented the first modern computer?",
        option_a="Germany",
        option_b="United States",
        option_c="United Kingdom",
        option_d="France",
        correct_option="B",
    ),
    Question(
        question_text="Who was the first woman to fly solo across the Atlantic Ocean?",
        option_a="Amelia Earhart",
        option_b="Bessie Coleman",
        option_c="Harriet Quimby",
        option_d="Jacqueline Cochran",
        correct_option="A",
    ),
    Question(
        question_text="What is the capital of Canada?",
        option_a="Ottawa",
        option_b="Toronto",
        option_c="Vancouver",
        option_d="Montreal",
        correct_option="A",
    ),
    Question(
        question_text="What is the tallest mountain in the world?",
        option_a="Mount Everest",
        option_b="K2",
        option_c="Kangchenjunga",
        option_d="Mount Kilimanjaro",
        correct_option="A",
    ),
    Question(
        question_text="Which is the largest continent?",
        option_a="Asia",
        option_b="Africa",
        option_c="North America",
        option_d="Europe",
        correct_option="A",
    ),
    Question(
        question_text="What is the national flower of the United States?",
        option_a="Rose",
        option_b="Lily",
        option_c="Tulip",
        option_d="Sunflower",
        correct_option="A",
    ),
    Question(
        question_text="What is the symbol for gold on the periodic table?",
        option_a="Ag",
        option_b="Au",
        option_c="Al",
        option_d="Ga",
        correct_option="B",
    ),
    Question(
        question_text="Who is known as the father of modern physics?",
        option_a="Isaac Newton",
        option_b="Albert Einstein",
        option_c="Niels Bohr",
        option_d="Galileo Galilei",
        correct_option="B",
    ),
    Question(
        question_text="Which country is home to the Great Barrier Reef?",
        option_a="Australia",
        option_b="United States",
        option_c="Mexico",
        option_d="Brazil",
        correct_option="A",
    ),
    Question(
        question_text="What is the longest river in the United States?",
        option_a="Mississippi River",
        option_b="Colorado River",
        option_c="Missouri River",
        option_d="Rio Grande",
        correct_option="C",
    ),
    Question(
        question_text="What is the capital of Italy?",
        option_a="Rome",
        option_b="Paris",
        option_c="Madrid",
        option_d="Athens",
        correct_option="A",
    ),
    Question(
        question_text="What is the primary ingredient in sushi?",
        option_a="Fish",
        option_b="Rice",
        option_c="Seaweed",
        option_d="Vegetables",
        correct_option="B",
    ),
    Question(
        question_text="What is the largest type of big cat?",
        option_a="Lion",
        option_b="Tiger",
        option_c="Jaguar",
        option_d="Leopard",
        correct_option="B",
    ),
    Question(
        question_text="Which country is famous for the invention of the windmill?",
        option_a="Netherlands",
        option_b="France",
        option_c="Germany",
        option_d="Belgium",
        correct_option="A",
    ),
    Question(
        question_text="What is the fastest animal on Earth?",
        option_a="Cheetah",
        option_b="Peregrine Falcon",
        option_c="Pronghorn Antelope",
        option_d="Lion",
        correct_option="B",
    ),
    Question(
        question_text="Which famous scientist discovered the laws of motion?",
        option_a="Isaac Newton",
        option_b="Galileo Galilei",
        option_c="Albert Einstein",
        option_d="Marie Curie",
        correct_option="A",
    ),
    Question(
        question_text="Who painted the famous artwork 'Mona Lisa'?",
        option_a="Vincent van Gogh",
        option_b="Claude Monet",
        option_c="Leonardo da Vinci",
        option_d="Pablo Picasso",
        correct_option="C",
    ),
    Question(
        question_text="Which country is the largest producer of coffee in the world?",
        option_a="Brazil",
        option_b="Colombia",
        option_c="Vietnam",
        option_d="United States",
        correct_option="A",
    ),
    Question(
        question_text="Who invented the telephone?",
        option_a="Alexander Graham Bell",
        option_b="Thomas Edison",
        option_c="Nikola Tesla",
        option_d="Guglielmo Marconi",
        correct_option="A",
    ),
    Question(
        question_text="Which country is home to the Eiffel Tower?",
        option_a="Italy",
        option_b="France",
        option_c="Germany",
        option_d="Spain",
        correct_option="B",
    ),
    Question(
        question_text="What is the tallest waterfall in the world?",
        option_a="Niagara Falls",
        option_b="Angel Falls",
        option_c="Victoria Falls",
        option_d="Iguazu Falls",
        correct_option="B",
    ),
    Question(
        question_text="Which planet is known as the Red Planet?",
        option_a="Mars",
        option_b="Venus",
        option_c="Earth",
        option_d="Jupiter",
        correct_option="A",
    ),
    Question(
        question_text="Which element is used to make pencils?",
        option_a="Lead",
        option_b="Graphite",
        option_c="Carbon",
        option_d="Silicon",
        correct_option="B",
    ),
    Question(
        question_text="What is the smallest planet in our solar system?",
        option_a="Mercury",
        option_b="Mars",
        option_c="Venus",
        option_d="Pluto",
        correct_option="A",
    ),
    Question(
        question_text="Which bird can fly backwards?",
        option_a="Hummingbird",
        option_b="Eagle",
        option_c="Pigeon",
        option_d="Sparrow",
        correct_option="A",
    ),
    Question(
        question_text="Which element is essential for the formation of bones and teeth?",
        option_a="Iron",
        option_b="Calcium",
        option_c="Magnesium",
        option_d="Sodium",
        correct_option="B",
    ),
    Question(
        question_text="What is the national animal of Australia?",
        option_a="Kangaroo",
        option_b="Koala",
        option_c="Wombat",
        option_d="Emu",
        correct_option="A",
    ),
    Question(
        question_text="Which city is known as the 'Big Apple'?",
        option_a="Los Angeles",
        option_b="Chicago",
        option_c="New York City",
        option_d="San Francisco",
        correct_option="C",
    ),
    Question(
        question_text="Who was the first human to journey into space?",
        option_a="Yuri Gagarin",
        option_b="Neil Armstrong",
        option_c="Buzz Aldrin",
        option_d="Valentina Tereshkova",
        correct_option="A",
    ),
    Question(
        question_text="Which chemical element is represented by the symbol 'Na'?",
        option_a="Sodium",
        option_b="Nitrogen",
        option_c="Neon",
        option_d="Nickel",
        correct_option="A",
    ),
    Question(
        question_text="Which country is known for its pyramids?",
        option_a="Egypt",
        option_b="Mexico",
        option_c="China",
        option_d="India",
        correct_option="A",
    ),
    Question(
        question_text="What is the capital city of Australia?",
        option_a="Sydney",
        option_b="Melbourne",
        option_c="Canberra",
        option_d="Brisbane",
        correct_option="C",
    ),
    Question(
        question_text="What is the largest mammal in the world?",
        option_a="Elephant",
        option_b="Blue Whale",
        option_c="Giraffe",
        option_d="Shark",
        correct_option="B",
    ),
    Question(
        question_text="Which famous physicist developed the theory of relativity?",
        option_a="Isaac Newton",
        option_b="Albert Einstein",
        option_c="Niels Bohr",
        option_d="Galileo Galilei",
        correct_option="B",
    ),
    Question(
        question_text="Which country is the birthplace of the game of chess?",
        option_a="India",
        option_b="China",
        option_c="Persia",
        option_d="Egypt",
        correct_option="A",
    ),
    Question(
        question_text="Which is the longest river in the world?",
        option_a="Amazon River",
        option_b="Nile River",
        option_c="Yangtze River",
        option_d="Mississippi River",
        correct_option="B",
    ),
    Question(
        question_text="Who painted the famous artwork 'Starry Night'?",
        option_a="Claude Monet",
        option_b="Vincent van Gogh",
        option_c="Pablo Picasso",
        option_d="Leonardo da Vinci",
        correct_option="B",
    ),
    Question(
        question_text="Which country is known as the Land of the Rising Sun?",
        option_a="China",
        option_b="Japan",
        option_c="South Korea",
        option_d="Vietnam",
        correct_option="B",
    ),
    Question(
        question_text="What is the name of the longest-running television show in the U.S.?",
        option_a="The Simpsons",
        option_b="Friends",
        option_c="The Office",
        option_d="The Tonight Show",
        correct_option="A",
    ),
    Question(
        question_text="Which city is the capital of France?",
        option_a="Paris",
        option_b="London",
        option_c="Berlin",
        option_d="Rome",
        correct_option="A",
    ),
    Question(
        question_text="What is the most common gas in Earth's atmosphere?",
        option_a="Oxygen",
        option_b="Carbon Dioxide",
        option_c="Nitrogen",
        option_d="Argon",
        correct_option="C",
    ),
    Question(
        question_text="What type of animal is the largest living creature in the world?",
        option_a="Shark",
        option_b="Elephant",
        option_c="Blue Whale",
        option_d="Giraffe",
        correct_option="C",
    ),
    Question(
        question_text="Which country is known for having the most pyramids?",
        option_a="Egypt",
        option_b="Sudan",
        option_c="Mexico",
        option_d="China",
        correct_option="B",
    ),
    Question(
        question_text="Which element has the chemical symbol 'H'?",
        option_a="Hydrogen",
        option_b="Helium",
        option_c="Oxygen",
        option_d="Carbon",
        correct_option="A",
    ),
    Question(
        question_text="Who was the first person to walk on the Moon?",
        option_a="Buzz Aldrin",
        option_b="Yuri Gagarin",
        option_c="Neil Armstrong",
        option_d="John Glenn",
        correct_option="C",
    ),
    Question(
        question_text="Which is the smallest continent by land area?",
        option_a="Asia",
        option_b="Australia",
        option_c="Europe",
        option_d="Antarctica",
        correct_option="B",
    ),
    Question(
        question_text="Which animal is known as the king of the jungle?",
        option_a="Lion",
        option_b="Tiger",
        option_c="Elephant",
        option_d="Giraffe",
        correct_option="A",
    ),
    Question(
        question_text="What is the currency of Japan?",
        option_a="Yuan",
        option_b="Won",
        option_c="Yen",
        option_d="Ringgit",
        correct_option="C",
    ),
    Question(
        question_text="Who is the author of the Harry Potter series?",
        option_a="J.R.R. Tolkien",
        option_b="J.K. Rowling",
        option_c="C.S. Lewis",
        option_d="George R.R. Martin",
        correct_option="B",
    ),
    Question(
        question_text="Which country is famous for the production of chocolate?",
        option_a="France",
        option_b="Germany",
        option_c="Belgium",
        option_d="Switzerland",
        correct_option="C",
    ),
    Question(
        question_text="What is the hardest natural substance on Earth?",
        option_a="Gold",
        option_b="Diamond",
        option_c="Iron",
        option_d="Platinum",
        correct_option="B",
    ),
    Question(
        question_text="Who invented the light bulb?",
        option_a="Nikola Tesla",
        option_b="Thomas Edison",
        option_c="Alexander Graham Bell",
        option_d="James Watt",
        correct_option="B",
    ),
    Question(
        question_text="What is the largest country by land area?",
        option_a="United States",
        option_b="China",
        option_c="Russia",
        option_d="Canada",
        correct_option="C",
    ),
    Question(
        question_text="What type of animal is a Komodo dragon?",
        option_a="Lizard",
        option_b="Snake",
        option_c="Crocodile",
        option_d="Alligator",
        correct_option="A",
    ),
    Question(
        question_text="Which ocean is the largest?",
        option_a="Atlantic Ocean",
        option_b="Indian Ocean",
        option_c="Arctic Ocean",
        option_d="Pacific Ocean",
        correct_option="D",
    ),
    Question(
        question_text="Which language has the most native speakers worldwide?",
        option_a="Mandarin Chinese",
        option_b="Spanish",
        option_c="English",
        option_d="Hindi",
        correct_option="A",
    ),
    Question(
        question_text="What is the chemical symbol for water?",
        option_a="CO2",
        option_b="H2O",
        option_c="O2",
        option_d="CH4",
        correct_option="B",
    ),
    Question(
        question_text="Who was the first woman to win a Nobel Prize?",
        option_a="Marie Curie",
        option_b="Rosalind Franklin",
        option_c="Ada Lovelace",
        option_d="Helen Keller",
        correct_option="A",
    ),
    Question(
        question_text="In which year did the Titanic sink?",
        option_a="1912",
        option_b="1905",
        option_c="1923",
        option_d="1930",
        correct_option="A",
    ),
    Question(
        question_text="What is the tallest building in the world?",
        option_a="Burj Khalifa",
        option_b="Empire State Building",
        option_c="Taipei 101",
        option_d="Shanghai Tower",
        correct_option="A",
    ),
    Question(
        question_text="Which country is home to the Eiffel Tower?",
        option_a="Germany",
        option_b="France",
        option_c="Italy",
        option_d="United Kingdom",
        correct_option="B",
    ),
    Question(
        question_text="Which country is known for the Taj Mahal?",
        option_a="China",
        option_b="India",
        option_c="Egypt",
        option_d="Turkey",
        correct_option="B",
    ),
    Question(
        question_text="What is the most common type of tree in the world?",
        option_a="Pine",
        option_b="Oak",
        option_c="Maple",
        option_d="Birch",
        correct_option="A",
    ),
    Question(
        question_text="Which animal is known for being able to regenerate lost body parts?",
        option_a="Starfish",
        option_b="Lizard",
        option_c="Octopus",
        option_d="Elephant",
        correct_option="A",
    ),
    Question(
        question_text="Which ocean is the smallest?",
        option_a="Atlantic Ocean",
        option_b="Indian Ocean",
        option_c="Arctic Ocean",
        option_d="Southern Ocean",
        correct_option="C",
    ),
    Question(
        question_text="Who is the Greek god of the sea?",
        option_a="Zeus",
        option_b="Apollo",
        option_c="Poseidon",
        option_d="Hades",
        correct_option="C",
    ),
    Question(
        question_text="Which country is famous for the invention of the windmill?",
        option_a="Netherlands",
        option_b="France",
        option_c="Germany",
        option_d="Denmark",
        correct_option="A",
    ),
    Question(
        question_text="What is the square root of 64?",
        option_a="6",
        option_b="7",
        option_c="8",
        option_d="9",
        correct_option="C",
    ),
    Question(
        question_text="Which planet is the hottest in the solar system?",
        option_a="Mercury",
        option_b="Venus",
        option_c="Mars",
        option_d="Jupiter",
        correct_option="B",
    ),
    Question(
        question_text="Which country is home to the Great Wall of China?",
        option_a="China",
        option_b="India",
        option_c="Japan",
        option_d="Korea",
        correct_option="A",
    ),
    Question(
        question_text="Which chemical element is used in the production of steel?",
        option_a="Iron",
        option_b="Copper",
        option_c="Lead",
        option_d="Gold",
        correct_option="A",
    ),
    Question(
        question_text="Which country invented pizza?",
        option_a="Italy",
        option_b="Greece",
        option_c="France",
        option_d="Spain",
        correct_option="A",
    ),
    Question(
        question_text="Which city is known as the Big Apple?",
        option_a="Los Angeles",
        option_b="Chicago",
        option_c="New York City",
        option_d="San Francisco",
        correct_option="C",
    ),
    Question(
    question_text="Who was the first Emperor of the Maurya Dynasty?",
    option_a="Chandragupta Maurya",
    option_b="Ashoka",
    option_c="Bindusara",
    option_d="Chandragupta II",
    correct_option="A",
    ),
    Question(
        question_text="What is the capital of the Indian state of Sikkim?",
        option_a="Gangtok",
        option_b="Kohima",
        option_c="Shillong",
        option_d="Itanagar",
        correct_option="A",
    ),
    Question(
        question_text="Which is the longest river in India?",
        option_a="Yamuna",
        option_b="Ganges",
        option_c="Godavari",
        option_d="Indus",
        correct_option="B",
    ),
    Question(
        question_text="Who is the first woman Prime Minister of India?",
        option_a="Sonia Gandhi",
        option_b="Indira Gandhi",
        option_c="Pratibha Patil",
        option_d="Rajkumari Amrit Kaur",
        correct_option="B",
    ),
    Question(
        question_text="Which Indian state has the largest area?",
        option_a="Uttar Pradesh",
        option_b="Madhya Pradesh",
        option_c="Rajasthan",
        option_d="Maharashtra",
        correct_option="C",
    ),
    Question(
        question_text="Who was the first Indian to win the Nobel Prize?",
        option_a="C. V. Raman",
        option_b="Rabindranath Tagore",
        option_c="Subrahmanyan Chandrasekhar",
        option_d="Har Gobind Khorana",
        correct_option="B",
    ),
    Question(
        question_text="What is the national animal of India?",
        option_a="Lion",
        option_b="Elephant",
        option_c="Tiger",
        option_d="Peacock",
        correct_option="C",
    ),
    Question(
        question_text="In which year did India gain independence?",
        option_a="1942",
        option_b="1947",
        option_c="1950",
        option_d="1952",
        correct_option="B",
    ),
    Question(
        question_text="Who is known as the 'Father of the Nation' in India?",
        option_a="Jawaharlal Nehru",
        option_b="Sardar Vallabhbhai Patel",
        option_c="Mahatma Gandhi",
        option_d="Subhas Chandra Bose",
        correct_option="C",
    ),
    Question(
        question_text="The Indian Institute of Technology (IIT) was established in which year?",
        option_a="1947",
        option_b="1950",
        option_c="1951",
        option_d="1956",
        correct_option="C",
    ),


    ]
    session.add_all(sample_questions)
    session.commit()

if __name__ == "__main__":
    engine = setup_database()
    Session = sessionmaker(bind=engine)
    session = Session()

    # Add sample questions to the database
    add_sample_questions(session)

    print("Sample questions added to the database.")
